name: ci-cd

on:
  push:
    tags:
      - "v*.*"

jobs:
  docker:
    env:
        USER: ${{ github.actor }}
        REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: | 
           ghcr.io/${{ env.REPO }}:latest
           ghcr.io/${{ env.REPO }}:${{ github.ref_name }}

      - name: Helm tool installer
        uses: Azure/setup-helm@v3

      - name: Helm Package
        run: |
          helm package drupal --version=${{ github.ref_name }} --app-version=${{ github.ref_name }} -d ./helm-releases
          helm repo index --url https://artsiomborisevich.github.io/devops-project/ --merge index.yaml .

      - name: Add generated helm to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b main
          git add .
          git commit -m "Generated by GitHub Action. Version ${{ github.ref_name }}"
          git push origin main   

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#            SLACK_CHANNEL: project_borisevich
#            SLACK_COLOR: ${{ job.status }}
#            SLACK_ICON: https://github.com/rtCamp.png?size=48
#            SLACK_MESSAGE: 'Post Content :rocket:'
#            SLACK_TITLE: 'New version of the project ${{ env.USER }}-${{ env.REPO }}-${{ github.ref_name }} has been released'
#            SLACK_USERNAME: Artiom Borisevich
#            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

